### ISSUE TITLE
some icons are rarely visible in dark mode

### ISSUE THREAD

**Issue by animeshbhakat** [ImAvinashSharma/ImAvinashSharma#1]
Globe (Website), Twitter, Linkedin, Instagram icons are rarely visible in default dark mode.

![Screenshot (840)](https://user-images.githubusercontent.com/60314168/118397576-53007d00-b672-11eb-9926-1e2fd1ad98dd.png)

**Comment by animeshbhakat** [comment]
The GitHub icon under the "Language and Tools" section is also not visible in default dark mode.

**Comment by ImAvinashSharma** [comment]
Thanks man 🚀
